on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-unknown-linux-musl
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin: target/release/pxx
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: target/release/pxx.exe
          - target: x86_64-apple-darwin
            os: macos-latest
            bin: target/release/pxx
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            bin: target/release/pxx
          - target: aarch64-apple-darwin
            os: macos-latest
            bin: target/release/pxx
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: proxy-exec-${{ matrix.target }}
          path: ${{ matrix.bin }}
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - uses: Swatinem/rust-cache@v1

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
