on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: target/release/pxx
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: target/release/pxx.exe
          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: target/release/pxx

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: proxy-exec-${{ matrix.target }}
          path: ${{ matrix.bin }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: stable

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
